### ISSUE TITLE
Feature request: haskell to javascript

### ISSUE THREAD

**Issue by flip111** [lambdabot/lambdabot#101]
I was trying to understand this:
```
flip id 2
-- then
flip id 2 <$> [(*2)]
```

it would be useful to see a javascript equivalent, something along the lines of:
```
function flipId(num) { return function(func) { return func(num); }; }
> undefined
a = flipId(2);
> function (func) { return func(num); }
b = a(function(Num) { return Num*2; })
> 4
```

Ok returning `[4]` and `4` is not exactly the same, so the example is not perfect but i hope i made the idea clear.

**Comment by int-e** [comment]
I don't think this will happen; JavaScript is not a very good nor attractive target language for Haskell code, and writing such a translation is a non-trivial undertaking. I know that there are Haskell compilers targeting Javascript, but their output is not pretty, to say the least, and therefore not suitable for Lambdabot.

**Comment by flip111** [comment]
The output not being pretty is a very reasonable argument. Yes i agree with you for a chatbot it would not be a good fit. Maybe better on a webpage. Thanks for your anwer.
