### ISSUE TITLE
Please add support for monad-control 1.x

### ISSUE THREAD

**Issue by peti** [lambdabot/lambdabot#105]
I would like to package `lambdabot` in Nixpkgs, but we have moved `monad-control` to version 1.x a while ago, which lambdabot unfortunately doesn't support: http://packdeps.haskellers.com/feed?needle=lambdabot-core. Is there any chance to get an updated version on Hackage that supports a recent version of that dependency?

**Comment by int-e** [comment]
Definitely. I consider the upper bound that is currently in place a temporary stop-gap measure. (there is another such upper bound for utf8-string; see #103)

**Comment by peti** [comment]
Very good! I'll be happy to package lambdabot in NixOS once the new version becomes available.

**Comment by int-e** [comment]
This will be fixed in the next release, thanks to @trofi (cf. #106).

**Comment by peti** [comment]
Is there a version available on Hackage that contains the fix?

**Comment by int-e** [comment]
I'm planning to release a new version on hackage the next weekend.

**Comment by int-e** [comment]
`lambdabot-5.0.1` is now available on hackage.
