### ISSUE TITLE
How can I solve this problem?: Could not find module `Lambdabot.Plugin.Eval.Trusted'

### ISSUE THREAD

**Issue by xnuk** [lambdabot/lambdabot#107]
```
# ghc -V
The Glorious Glasgow Haskell Compilation System, version 7.6.3
# lambdabot -V
lambdabot version 5.0
# lambdabot
[NOTICE] : Initialising plugins
[NOTICE] : Done loading plugins
lambdabot> > 1+1
 L.hs:63:8:
     Could not find module `Lambdabot.Plugin.Eval.Trusted'
     Use -v to see a list of the files searched for.
```

Using Ubuntu 14.04.2 x64.

**Comment by mokus0** [comment]
It looks to me like your L.hs is outdated.  It also looks like there's an issue with initializing state (Lambdabot.File is pulling resources from Paths_lambdabot_core but the initial state files are stored in Paths_lambdabot), so for now the right solution is probably to copy <cabal_dir>/share/x86_64-linux-ghc-7.6.3/lambdabot-5.0/State/Pristine.hs to .lambdabot/State/Pristine.hs and then run `undefine` in lambdabot to reset the evaluation context.

**Comment by int-e** [comment]
To clarify, the target directory for `Pristine.hs` is `~/.lambdabot/State/`, while `/share` is relative to cabal's installation prefix, usually `~/.cabal` for user installations, `/usr/local` for global installations or `.cabal-sandbox` for installations inside a sandbox.

**Comment by xnuk** [comment]
It works! Thank you so much!
