### ISSUE TITLE
State initialization pulls from incorrect location

### ISSUE THREAD

**Issue by mokus0** [lambdabot/lambdabot#108]
Lambdabot.File is pulling resources from Paths_lambdabot_core rather than Paths_lambdabot.  This causes initialization of many modules to fail on a clean install.

The solution that looks best to me at first glance is to create an additional config var in lambdabot_core that specifies the location (or even a search path) of the default state files, and is filled in by the Main module in the lambdabot module to tell the core where to find the files.

**Comment by mokus0** [comment]
This should be a pretty easy fix, I'll try to get to it after work or maybe this weekend if nobody else jumps on it first.

**Comment by int-e** [comment]
Thanks for looking into this! It would be good to have a test for this kind of problem. (I'll try to think of one. In any case I'll test a pristine install without a populated ~/.lambdabot for the next release.)

**Comment by int-e** [comment]
Fixed by dd28cc350b0f73b0c85b630e9903fc397499fede.
