### ISSUE TITLE
Lambdabot is not sentient

### ISSUE THREAD

**Issue by treeowl** [lambdabot/lambdabot#114]
Early researchers made great strides in artificial intelligence using such languages as Prolog and Lisp. Since Haskell is more powerful than these languages, there is no excuse for Lambdabot not to be able to think on its own.

**Comment by int-e** [comment]
Good point. Perhaps we could borrow some code from https://github.com/fis/fungot.

**Comment by treeowl** [comment]
Do you think that will be sufficient to allow lambdabot to demonstrate awareness and perhaps interact in natural language? If it could even give it a sense of moral behavior, I suppose that would be an improvement.

**Comment by treeowl** [comment]
April Fools!
