### ISSUE TITLE
Point Free Data.Composition Support

### ISSUE THREAD

**Issue by Fresheyeball** [lambdabot/lambdabot#119]
```
@pl (\x y z -> x <> y <> z)
```

returns 

```
((<>) .) . (<>)
```

but why not

```
((<>) .* (<>))
```

?

**Comment by int-e** [comment]
That `.*` operator is not standard. (The most standard name for it appears to be `.:`, and even that isn't all that common.) So I suggest we leave this as is.

**Comment by Fresheyeball** [comment]
I dunno. I run `@pl` alot just to see what shakes out, and often `. ) .` shows up somewhere and is really just `.:`. Isn't a point (pun intended) of `@pl` to facilitate learning of how to compose functions?
