### ISSUE TITLE
Dependencies need updates for GHC 7.10

### ISSUE THREAD

**Issue by mokus0** [lambdabot/lambdabot#120]
Creating this more as a common place to track this.  We might have to take over ownership of a couple orphaned packages that originally spun off lambdabot quite some time ago.

As an indication of what still needs to be updated, this gist is an ugly but working Docker build.  It builds a few dependencies from git, monkeypatches some others, etc., to get lambdabot running on ghc-7.10 in a docker container:

https://gist.github.com/mokus0/bc9cdeb16e57d11c336b

**Comment by adamflott** [comment]
+1

I'm definitely looking forward to getting a cleaner lambdabot with 7.10. I use a slightly odd setup that is preventing me from getting my bot compiled. Currently it's having trouble getting all the dependencies ordering right when I sloppily hacked the dockerfile.

I use Arch Linux which just added 7.10, a few dozen lambdabot plugins, and a quirky home-grown plugin to connect to my XMPP server. If I get the energy and courage maybe I'll clean it up and release it. My chat room feels naked without my bot!

**Comment by int-e** [comment]
We'll have to deal with this soonish; there's a ghc-7.10.2 RC, and it looks like the haskell-platform is going to be updated to ghc-7.10 as well.

The most significant dependency holding us back is mueval (see also https://github.com/gwern/mueval/issues/9). Furthermore, misfortune fails to build with ghc-7.10.1.

**Comment by int-e** [comment]
I just did a test build with ghc-7.10.1; as far as I can see, all dependencies have been taken care of (even mueval)

**Comment by l29ah** [comment]
@adamflott do you feel like releasing your plugin?
