### ISSUE TITLE
lambdabot responds to every comment in channel

### ISSUE THREAD

**Issue by cengique** [lambdabot/lambdabot#121]
Hi,

After a recent upgrade to 5.0.2.2 (although @version still reports 5.0.1), lambdabot responds with a vixen message to every like in the channel, which is very annoying! I tried starting with a clean State, but didn't change anything. Is there a way to disable this behavior?

**Comment by int-e** [comment]
I don't see any change that would affect the behavior of the vixen module between versions 5.0.1 and 5.0.2.2; a more likely case would be the update from 5.0 to 5.0.1, which probably made finding its data file more reliable. I'd suggest disabling the plugin (by using  cabal unpack lambdabot  and changing src/Modules.hs, where you can remove it from the line that mentions `noveltyPlugins`.

That said I thought that the module only replies if lambdabot is addressed specifically. I need to find some time to test this.

Btw, nice catch about the version. It currently prints the version of the lambdabot-core package, which didn't change...

**Comment by cengique** [comment]
Yes, my last version was 4.3.X, so it was a major upgrade! Looking through the code in `novelty-plugins`, I realized vixen has two additional commands: `vixen-on` and `vixen-off`. Issuing `@vixen-off` solved the problem for me! Although I don't understand how the recent changes turned this on. 

And also for some reason this command does not show up in the response to `@list vixen`, which only gives `vixen`. 

Glad to be of service, I'm glad to see you're still maintaining this package!

**Comment by int-e** [comment]
Since `@vixen-off` and `@vixen-on` are admin commands, `@list` does not show them.
I'm not sure what to do about this, except writing documentation.
Perhaps the contextual responses of the `vixen` module should just be off by default.

**Comment by cengique** [comment]
Yeah, especially if you can confirm the problem exists for you also.

**Comment by cengique** [comment]
Thanks for the workaroundn. Although the correct solution would be to fix vixen to properly respond only in context.
