### ISSUE TITLE
@index doesn't know where Applicative is

### ISSUE THREAD

**Issue by neongreen** [lambdabot/lambdabot#122]
~~~
22:48 <indiagreen> @index Monad
22:48 <lambdabot> Control.Monad, Prelude, Control.Monad.Reader, Control.Monad.Writer, Control.Monad.State, Control.Monad.RWS, Control.Monad.Identity, Control.Monad.Cont, Control.Monad.Error, Control.Monad.List

22:48 <indiagreen> @index Applicative
22:48 <lambdabot> bzzt

22:47 <indiagreen> @index pure
22:47 <lambdabot> Control.Arrow
~~~

**Comment by neongreen** [comment]
Where is the list of modules `@index` knows about, anyway?

**Comment by int-e** [comment]
It's in a file called `haddock` shipped with lambdabot (`lambdabot/State/haddock` in the repository; if you installed lambdabot, you can find it in its data directory, and you can put your own copy in lambdabot's state directory (usually `~/.lambdabot/State`)). The file is a gzip-d text file in a straight-forward format, but I don't know how it was created.

**Comment by int-e** [comment]
Thanks for the report! I don't think I would've looked at updating the `haddock` file otherwise, and in the end it was surprisingly easy to recreate the index.
