### ISSUE TITLE
build with utf8-string-1

### ISSUE THREAD

**Issue by DanBurton** [lambdabot/lambdabot#127]
There are two packages that have an upper bound of `< 1`:

* lambdabot-haskell-plugins-5.0.2.1
* lambdabot-reference-plugins-5.0.2.1

Once this is fixed, lambdabot should be pretty much ready to join stackage. See: https://github.com/fpco/stackage/pull/705.

**Comment by int-e** [comment]
This is fixed in git, cf. #110 and #120. I've been waiting for ghc-7.10.2 to materialize to make a release, which has been taking longer than expected.

**Comment by DanBurton** [comment]
Would you consider making a sooner release? I presume at this point that not much is going to diverge from the ghc-7.10.2 release candidate, but I don't really know what's going on there.

**Comment by int-e** [comment]
Done, cf. https://hackage.haskell.org/package/lambdabot-5.0.3
