### ISSUE TITLE
@pl pretty printer chokes on qualified operators

### ISSUE THREAD

**Issue by lspitzner** [lambdabot/lambdabot#128]
~~~~
@pl \b -> (\c -> ((Control.Monad.>>=) c) (\g -> Control.Applicative.pure (b g)))
flip (Control.Monad. >>=) . (Control.Applicative.pure .)
~~~~

but should be

~~~~
flip (Control.Monad.>>=) . (Control.Applicative.pure .)
~~~~

related is https://github.com/bmillwood/pointfree/issues/11, but i think the issue is in lamdabot's prettyprinter (?).

~~~~
@version
<lambdabot> lambdabot 5.0.2.2
~~~~

**Comment by int-e** [comment]
Thanks for the report. For what it's worth, it looks like a parsing issue to me:

~~~
@pl (foo Bar.>>= baz)
<lambdabot>  baz =<< foo  Bar.
~~~

In any case it should be easy to fix, I'll take care of it in a couple of days.

**Comment by lspitzner** [comment]
nice; thanks!
