### ISSUE TITLE
Please add support for latest versions of dependent-map and dependent-sum 

### ISSUE THREAD

**Issue by peti** [lambdabot/lambdabot#132]
http://packdeps.haskellers.com/feed?needle=lambdabot-core

**Comment by DanBurton** [comment]
This appears to be implemented in the repo, it just hasn't been uploaded yet.

https://github.com/lambdabot/lambdabot/blob/master/lambdabot-core/lambdabot-core.cabal#L74-L75

**Comment by morpheusbeing** [comment]
Hmm, as ancient beginner, how can replace the cabal installed version with the github version to help with testing?

**Comment by DanBurton** [comment]
@morpheusbeing You can try using [stack](https://github.com/commercialhaskell/stack#readme), which makes it easy to specify and retrieve dependencies on a per-project basis. See the stack wiki for details on how to depend on a package from github: https://github.com/commercialhaskell/stack/wiki/stack.yaml#packages

**Comment by int-e** [comment]
Indeed this is implemented in the repo; I'll release a new version on hackage this weekend.

**Comment by DanBurton** [comment]
bump

**Comment by juhp** [comment]
ping :)

**Comment by DanBurton** [comment]
re-ping @int-e.

**Comment by clinty** [comment]
whee

**Comment by int-e** [comment]
I finally made a release. Sorry for keeping you waiting!
