### ISSUE TITLE
@free command is very brittle

### ISSUE THREAD

**Issue by mpickering** [lambdabot/lambdabot#143]
There seems to be a lot of partial code in the `@free` command.

Here is a conversation with lambdabot which displays two of the issues.

```
8:53 PM <mpickering> @free
8:53 PM <lambdabot> Pattern match failure in do expression at src/Lambdabot/Plugin/Haskell/Free/FreeTheorem.hs:54:21-35
8:54 PM <mpickering> @free (a -> b) ->  F a -> F b
8:54 PM <lambdabot> Pattern match failure in do expression at src/Lambdabot/Plugin/Haskell/Free/FreeTheorem.hs:54:21-35
8:55 PM <mpickering> @free fmap :: (a -> b) ->  F a -> F b
8:55 PM <lambdabot> g . h = k . f => $map_F g . fmap h = fmap k . $map_F f
8:56 PM <mpickering> @free dimap :: (b -> a) -> (c -> d) -> P b c -> P a d
8:56 PM <lambdabot> Plugin `free' failed with: src/Lambdabot/Plugin/Haskell/Free/FreeTheorem.hs:(202,1)-(291,24): Non-exhaustive patterns in function freeTheorem'
```

**Comment by int-e** [comment]
New output:

    lambdabot> @free
    Try `free <ident>` or `free <ident> :: <type>`
    lambdabot> @free (a -> b) ->  F a -> F b
    Try `free <ident>` or `free <ident> :: <type>`
    lambdabot> @free fmap :: (a -> b) ->  F a -> F b
    g . h = k . f => $map_F g . fmap h = fmap k . $map_F f
    lambdabot> @free dimap :: (b -> a) -> (c -> d) -> P b c -> P a d
    Plugin `free' failed with: Sorry, this type is too difficult for me.

I don't understand the actual free theorem code, so I don't know what to do in the last case. There's special handling for `Either` in that code, but only unary type constructors otherwise.
