### ISSUE TITLE
@unpl adds an unnecessary semicolon sometimes

### ISSUE THREAD

**Issue by 23Skidoo** [lambdabot/lambdabot#144]
Consider the following session:

```
> @unpl f (filter ('a' ==) x)
f (filter (\ a -> 'a' == a) x)
> @unpl h x = f (filter ('a' ==) x)
h x = f (filter (\ a -> 'a' == a) x);
```

The second command results in an unnecessary semicolon being added to the output for some reason.

Originally reported [here](https://github.com/23Skidoo/pointful/issues/9).

**Comment by int-e** [comment]
The printed code is valid Haskell, so there's no bug. I agree that the output here could be prettier, but it's not lambdabot's code anyway. All lambdabot does is

    import Language.Haskell.Exts
    
    prettyPrintInLine = prettyPrintWithMode (defaultMode { layout = PPInLine })

so it's up to the `Pretty` instance for the `Decl` type in `haskell-src-exts`.

**Comment by int-e** [comment]
PS the following example may be a bit more convincing:

    Language.Haskell.Exts> let ParseOk x = parseExp "let f 0 = 1; f x = 1; g y = y in f . g"
    Language.Haskell.Exts> prettyPrintWithMode (defaultMode { layout = PPInLine }) x
    "let { f 0 = 1;f x = 1;; g y = y;} in f . g"

**Comment by 23Skidoo** [comment]
Thanks, opened a ticket at the `haskell-src-exts` bug tracker: https://github.com/haskell-suite/haskell-src-exts/issues/309.
