### ISSUE TITLE
Undefine a single definition

### ISSUE THREAD

**Issue by nitrix** [lambdabot/lambdabot#148]
This is going to be tedious, probably to do with touching the L.hs file, but I so often wish we could just undefine a single symbol and not all of them.

It rarely happens, but there are moments were we step on each others toes a little.

**Comment by int-e** [comment]
yes, that sounds useful (```@undef foo``` would be a natural UI), but indeed tedious to implement.

**Comment by nitrix** [comment]
@int-e Challenge accepted :]
