### ISSUE TITLE
Bump dependency-sum version

### ISSUE THREAD

**Issue by abbradar** [lambdabot/lambdabot#158]
lambdabot-core builds with dependent-sum 0.4.

**Comment by int-e** [comment]
cf. https://github.com/mokus0/dependent-sum-template/issues/7

**Comment by int-e** [comment]
Note that this will have to be resolved for lambdabot to build with ghc-8.0.2.

**Comment by JonCoens** [comment]
As we wait weeks for an update (I disagree in the other thread that 2 weeks isn't a lot of time), anyone feel like seeing how bad it would be to remove this dependency from lambdabot?

**Comment by JonCoens** [comment]
`dependent-sum-template` has updated their bounds

**Comment by int-e** [comment]
After a long wait, lambdabot has a green Travis badge again!
