### ISSUE TITLE
Tab completion for definitions?

### ISSUE THREAD

**Issue by ajm188** [lambdabot/lambdabot#161]
This is a terrible idea I had today, but I thought I would at least offer it up for discussion.

What if, when a user `@define`s something, lambdabot spawned a subprocess to join the channel with a nick equal to that definition? Then users would be able to use tab completion for definitions in the channel.

I'm like 10% serious about this, but do let me know your thoughts.

**Comment by int-e** [comment]
Sorry, but this is just insane. Technical difficulties aside (every nick would require a new connection to the IRC server), it's inviting abuse (`@let ajm188 = 42` anyone?) and would make lambdabot very noisy for people who see joins and parts.
