### ISSUE TITLE
Plugin `source' failed with: state not initialized

### ISSUE THREAD

**Issue by l29ah** [lambdabot/lambdabot#185]
Occurs on a fresh lambdabot installation on any `@src` invocation.

**Comment by int-e** [comment]
How did you install lambdabot? What is the platform? This works fine when installing lambdabot on Linux (Debian) with `cabal-install` for me, both with `v1-install` and `v2-install`. It even works with a sandbox and `v1-install`.

For lambdabot to find the state files, it uses Cabal's [data-files](https://www.haskell.org/cabal/users-guide/developing-packages.html#pkg-field-data-files) mechanism, so perhaps that is somehow broken in your setup.

**Comment by int-e** [comment]
I can't reproduce this. Feel free to reopen if you have more information.

**Comment by swamp-agr** [comment]
I am able to reproduce the issue.
GHC 8.10.7, cabal-jnstall 3.6.2.0.
See https://github.com/swamp-agr/lambdabot-telegram-plugins for more details of invokation.

**Comment by swamp-agr** [comment]
While every single command from other plugin is working fine, here I see:

```
Plugin `Telegram' failed with: state not initialized
CallStack (from HasCallStack):
  error, called at src/Lambdabot/Module.hs:87:37 in lambdabot-core-5.3.0.2-71cd153df97d788d3eaa43c05a5cf526f2f7f3528d913095da71816985f88651:Lambdabot.Module
```

**Comment by swamp-agr** [comment]
Ok, I think I see how it should be configured.

**Comment by int-e** [comment]
> Ok, I think I see how it should be configured. Copying `State/source` into `datadir` solved the configuration issue.

Right. This can be accomplished with `cabal-install` using the `data-files` directive. For reference, the relevant bit in lambdabot lives in `lambdabot.cabal`:

https://github.com/lambdabot/lambdabot/blob/07e548c4f1674bfb2c8678ef00cdac47a9b678e3/lambdabot/lambdabot.cabal#L37-L42

The corresponding logic that picks these files up is in `lambdabot-core`:

https://github.com/lambdabot/lambdabot/blob/07e548c4f1674bfb2c8678ef00cdac47a9b678e3/lambdabot-core/src/Lambdabot/File.hs#L48-L55
