### ISSUE TITLE
@type doesn't handle Unicode properly

### ISSUE THREAD

**Issue by ehird** [lambdabot/lambdabot#62]
It seems to be writing a `String` that's actually a `ByteString` (i.e. it has codepoints that are encoded as multiple bytes as multiple `Char`s in the list) to the GHCi `Handle`, or something. This has been the case forever, I think; not a new bug by any means, but it seems important enough to document, given that `@run` gets it right (as long as your locale is set correctly).

**Comment by int-e** [comment]
For now at least I went into the opposite direction: IRC messages are treated in a byte-oriented way by lambdabot and plugins are responsible for treating them as UTF-8 encoded unicode. My main justification (besides laziness) for this is that IRC is specified as a byte-oriented protocol, but it's possible to reconsider this at some point in the future.

**Comment by int-e** [comment]
I'm not sure why I didn't close this in 2016.
