### ISSUE TITLE
Vixen / Novelty Plugin failed to load

### ISSUE THREAD

**Issue by MaxDaten** [lambdabot/lambdabot#81]
with the current head in a cabal sandbox running 'lambdabot' crashes with:

```plain
[NOTICE] : Initialising plugins
[ERROR] : Module "vixen" failed to load.  Exception thrown: demandInput: not enough bytes
exception:
user error (Refusing to load due to a broken plugin)
```

any missing dependencies or config-files?

quick-fix: comment the novelty plugins line in `src/Modules.hs` out

**Comment by int-e** [comment]
This seems to be caused by #108.

**Comment by int-e** [comment]
This will be fixed in the next release. (See #108)
