### ISSUE TITLE
Could not find module `Network.URI' and missing PatBind slot

### ISSUE THREAD

**Issue by cengique** [lambdabot/lambdabot#90]
Because of recent changes in dependent packages, lambdabot no longer compiles. The `network` package has been split into two pieces since version 2.6, so the `lambdabot.cabal` file requires adding `network-uri` to the `build-depends` list. Otherwise both `network` and `network-uri` must be installed with versions <2.6.

There is a second problem coming from the haskell-src-exts package that came with a new version two weeks ago. They decided to reduce the number of arguments of PatBind from 5 to 4, which breaks things. The solution to install it version <1.16.

So this still builds and installs `lambdabot` correctly:

```
cabal install -j5  --constraint='network < 2.6' --constraint='network-uri < 2.6' --constraint='haskell-src-exts < 1.16' --force-reinstalls lambdabot
```

**Comment by int-e** [comment]
The fix is now on hackage.
