### ISSUE TITLE
Does not build against haskell-src-exts > 1.15.0.1

### ISSUE THREAD

**Issue by dcespin** [lambdabot/lambdabot#93]
When compiling lambdabot-haskell-plugins, the constructor 'UnGuardedAlt' is not in scope, as it appears to not be exported by haskell-src-exts 1.16.0. I was able to build it by putting an upper bound on haskell-src-exts in the build-depends in the cabal file.

EDIT: Additionally, lambdabot-network-plugins seems to need 'network-uri' in the build-depends in order to build successfully.

**Comment by treeowl** [comment]
Shouldn't this be fixed by either changing `haskell-src-exts` or fixing `lambdabot-haskell-plugins` so it doesn't need that constructor? Putting an upper bound on is a short-term thing to keep Hackage in order.

**Comment by int-e** [comment]
This was fixed by https://github.com/lambdabot/lambdabot/commit/fa6c3535db339886276bfe31ba96bcec24920cf1
