### ISSUE TITLE
Submit to Stackage

### ISSUE THREAD

**Issue by houshuang** [lambdabot/lambdabot#94]
Would be amazing if this could be integrated with Stackage - right now I am unable to build because of issues with 7.8.3, etc. Stackage could highlight these kinds of issues more quickly. Looking forward to Lambdabot awesomeness in my ghci :)

**Comment by rvion** [comment]
+1

**Comment by int-e** [comment]
I'm not sure about this. (I don't use Stackage; who is going to maintain this kind of metadata?)

**Comment by rvion** [comment]
If you want, you can give stackage a try just to see if it is positive for you :)

There is no metadata to maintain, you don't even have to change anything in lambdabot.
You'll just have free bug report as soon as lambdabot doesn't build with up-to-date packages, that's all.
Also, you'll ease the community to hack on lambdabot.

Instructions are here: http://www.stackage.org/ (Package Authors section)
(you just have to add your name and your package name in a file, and do a PR. You can even do all that from github, maximum 3 minutes)

**Comment by rvion** [comment]
btw, just in case you want to test:

With [Stack](https://github.com/commercialhaskell/stack), in one command or 2, people will be able to start contributing to lambdabot directly, even without ghc on their machine prior to that (automatic download and install of current ghc and dependencies for whatever version of lambdabot they want to use )

**Comment by DanBurton** [comment]
Lambdabot has a handful of obscure dependencies that aren't in stackage yet. Perhaps it would be wise to select a few of the more well maintained deps (that aren't in stackage yet) and add them to stackage first.

I've written a `stack.yaml` file that allows stack to build this repo. It lists all of the non-stackage dependencies and the versions that worked for my build.

I'm happy to help get lambdabot onto stackage as well.

**Comment by nomeata** [comment]
I was just about to report the same thing. The debian maintainers would benefit a lot if lambdabot and its dependencies are part of stackage, due to the extra QA this provides.

**Comment by int-e** [comment]
@nomeata: thanks, that convinces me that submitting to stackage would actually be worthwhile.

But as DanBurton wrote, the list of dependencies that are not yet on stackage is a bit daunting: 
(relative to stackage-nightly-2015-06-17, and excluding a few runtime dependencies like djinn) IOSpec-0.3, QuickCheck-safe-0.1.0.1, Stream-0.4.7.2, arrows-0.4.4.1, brainfuck-0.1.0.2, dependent-map-0.1.1.3, dependent-sum-0.2.1.0, dependent-sum-template-0.0.0.3, dice-0.1, hstatsd-0.1, knob-0.1.1, lazysmallcheck-0.6, mueval (git), misfortune-0.1.1.2, oeis-0.3.6, show-0.6, unlambda-0.1.4.1

I suppose we could shorten the list significantly by concentrating on the bare essentials (namely, just the haskell and irc plugins)

**Comment by mokus0** [comment]
Several of those are mine, and I'd like to get them on stackage at some point.  Guess I should get to that.

**Comment by clinty** [comment]
@mokus0 please do!

**Comment by DanBurton** [comment]
I've taken the liberty of putting the PR under my own name for now. https://github.com/fpco/stackage/pull/705

I'll open up relevant issues. If anyone would like to take responsibility for the lambdabot package (or any of its dependencies) on stackage, let me know and I can help make the appropriate alterations to the build-constraints.yaml file.

**Comment by mokus0** [comment]
I've added myself for a few of my dependencies (we'll see how the build goes, it's in progress now but I would hope if lambdabot builds then so do its dependencies).  It looks like build-constraints.yml also has room for setting up groups of users to be notified - I don't have a ton of time but I'm willing to be included on something like that and pitch in when possible to deal with breakages.

**Comment by DanBurton** [comment]
@mokus0 I took you up on your willingness to be pinged by lambdabot issues as detected by stackage:

https://github.com/fpco/stackage/commit/01bd274c686bc3a83fd600127b01325454c16b8f

If anyone else would like to be pinged, let me know and I'll add you to the list. Also, if anyone wants to take responsibility (in terms of Stackage) for each package directly, I can help you do that too.

At this point it is accurate to say that "lambdabot has been added to Stackage."

**Comment by nomeata** [comment]
Why is this closed? lambdabot is not in stackage (it might have been at some point). Or was it decided that lambdabot should not be in stackage?

**Comment by int-e** [comment]
I closed this because the last comment says that lambdabot has been added to stackage. It got removed again, but that's a problem that won't be resolved by keeping *this* issue open.

**Comment by DanBurton** [comment]
My take is that lambdabot isn't necessarily kept up to date at the pace expected for packages in stackage. I removed it from being listed under my name. If someone else wants to put it under theirs, and take responsibility for making releases more promptly, feel free to add it back under your name.
