### ISSUE TITLE
@google mis-parses scientific notation

### ISSUE THREAD

**Issue by tangentstorm** [lambdabot/lambdabot#98]
Asking:
    @google seconds in a century
returns:
    3.1556926 × 10

I don't actually know what it's parsing, but when I search in google manually, I get a conversion widget pre-populated with the values "1 century =  3.15569e9 second", so I suspect this is just error in the way scientific notation is parsed.

**Comment by int-e** [comment]
The following command mimics the query issued by lambdabot for conversion queries:

    curl -D /dev/stdout -A 'haskell-HTTP/4000.1.2' -e 'http://www.google.com/' "http://www.google.com/search?hl=en&q=seconds+in+a+century"

The part that  `@google` is trying to parse is this: `<h2 class="r" style="display:inline;font-size:138%">1 century = 3.1556926 &#215; 10<sup>9</sup> seconds</h2>`.
Dealing with `<sup>` in full generality is out of the question, but perhaps we could have a special case for `10<sup>n</sup>`.
